# Create enviroment for testing export-sis-alma.
version: "3.7"
services: 
    sftp:
        image: alpine:sftp
        container_name: "${CONTAINER_NAME:-sftp}"
        env_file: .env
        build:
            context: .
            args:
                - SFTP_UID=1000
                - SFTP_GID=1000
                - SFTP_USERNAME=user
                - SFTP_PASSWORD=sftp
        volumes:
            - ./private:/etc/ssh/private:ro
            - ./sshd_config:/etc/ssh/sshd_config:ro
            - "./sftp:/home/${SFTP_USERNAME}"
        ports:
            - "${PORT:-2222}:22"

