# Create enviroment for testing export-sis-alma.
version: "3.7"
services: 
    sftp:
        image: alpine:latest
        container_name: "${CONTAINER_NAME:-sftp}"
        build: .
        volumes:
            - ./private:/etc/ssh/private:ro
            - ./sshd_config:/etc/ssh/sshd_config:ro
            - ./home:/home/sftp:rw
        ports:
            - "${PORT:-2222}:22"
        restart: always

