version: "3.7"
services: 
    http-proxy:
        image: nginx:alpine
        container_name: http-proxy
        volumes:
            - ./volumes/http-proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./volumes/http-proxy/docker-entrypoint.d:/docker-entrypoint.d:ro
            - ./volumes/log:/var/log/nginx:rw
        networks:
            - app-network
            - app-internal
        ports:
            - 80:80
        depends_on:
            - http-site
            - http-cdn
        links: 
            - http-site
            - http-cdn
        restart: always

    http-cdn:
        image: nginx:alpine
        container_name: http-cdn
        volumes:
            - ./volumes/http-cdn/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./volumes/http-cdn/docker-entrypoint.d:/docker-entrypoint.d:ro
            - ./volumes/log:/var/log/nginx:rw
            - ./volumes/http-cdn/www:/var/www:ro
        networks: 
            - app-internal
        ports:
            - 8081:80
        restart: always

    http-site:
        image: nginx:alpine
        container_name: http-site
        volumes:
            - ./volumes/http-site/nginx.conf:/etc/nginx/conf.d/default.conf:ro            
            - ./volumes/http-site/docker-entrypoint.d:/docker-entrypoint.d:ro
            - ./volumes/log:/var/log/nginx:rw
            - ./volumes/http-site/www:/var/www:ro
        networks:
            - app-internal
        ports:
            - 8082:80
        restart: always

networks:
    app-network:
        driver: bridge
        internal: false
        
    app-internal:
        driver: bridge
        internal: true        