version: "3.7"
services: 
    proxy:
        image: nginx:alpine
        container_name: proxy
        volumes:
            - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./proxy/docker-entrypoint.d:/docker-entrypoint.d:ro
            - ./log:/var/log/nginx:rw
        networks:
            - app-network
            - app-internal
        ports:
            - 80:80
        depends_on:
            - site
            - cdn
        links: 
            - site
            - cdn
        restart: always

    cdn:
        image: nginx:alpine
        container_name: cdn
        volumes:
            - ./cdn/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./cdn/docker-entrypoint.d:/docker-entrypoint.d:ro
            - ./cdn/www:/var/www:ro
            - ./log:/var/log/nginx:rw
        networks: 
            - app-internal
        ports:
            - 8081:80
        restart: always

    site:
        image: nginx:alpine
        container_name: site
        volumes:
            - ./site/nginx.conf:/etc/nginx/conf.d/default.conf:ro            
            - ./site/docker-entrypoint.d:/docker-entrypoint.d:ro
            - ./log:/var/log/nginx:rw
            - ./site/www:/var/www:ro
        networks:
            - app-internal
        ports:
            - 8082:80
        restart: always

networks:
    app-network:
        driver: bridge
        internal: false
        
    app-internal:
        driver: bridge
        internal: true        