# Docker compose file for project.
# This setup includes a front facing proxy that reroutes traffic to cdn and site sercvices on an internal network. 
# Proxy also handles routing to the API services which is on both public/private networks due to required access 
# to external  services.
version: "3.3"
services:
    http-proxy:
        image: "nginx:alpine"
        container_name: "http-proxy"
        volumes:
            - ./volumes/http-proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro            
            - ./volumes/http-proxy/ssl:/etc/ssl/private:ro            
            - ./volumes/http-proxy/docker-entrypoint.d:/docker-entrypoint.d:ro
            - ./volumes/log:/var/log/nginx:rw
        networks:
            - app-external
            - app-internal
        ports:
            - 80:80
            - 443:443
        restart: always
        depends_on:
            - http-site
            - database
        links: 
            - http-site
            - database

    http-cdn:
        image: "nginx:alpine"
        container_name: "http-cdn"
        volumes:
            - ./volumes/http-cdn/nginx.conf:/etc/nginx/conf.d/default.conf:ro            
            - ./volumes/http-cdn/docker-entrypoint.d:/docker-entrypoint.d:ro
            - ./volumes/log:/var/log/nginx:rw
            - ./volumes/http-cdn/www:/www:ro
        networks:
            - app-internal            
        ports:
            - 80:80
        restart: always            

    http-site:
        image: "nginx:alpine"
        container_name: "http-site"
        volumes:
            - ./volumes/http-site/nginx.conf:/etc/nginx/conf.d/default.conf:ro            
            - ./volumes/http-site/docker-entrypoint.d:/docker-entrypoint.d:ro
            - ./volumes/log:/var/log/nginx:rw
            - ./volumes/http-site/www:/site/www:ro
        depends_on:
            - php-fpm
        links:
            - php-fpm
        networks:
            - app-internal
        ports:
            - 80:80
        restart: always

    php-fpm:
        image: "php:7.4-fpm-alpine"
        container_name: "php-site"
        volumes:
            - ./volumes/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
            - ./volumes/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
            - ./volumes/php-fpm/config.ini:/usr/local/etc/php/conf.d/config.ini:ro
            - ./volumes/http-site/www:/site/www:ro
            - ./volumes/http-site/include:/site/include:ro
            - ./volumes/http-site/view:/site/view:ro
        networks:
            - app-internal
        restart: always

    database:
        image: mariadb:latest
        container_name: "database"
        env_file: env/database
        volumes:
            - ./volumes/database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
            - ./volumes/database/data:/var/lib/mysql:rw
        networks: 
            - app-internal
        ports:
            - 3306:3306
        restart: always
        
    siege:        
        build:
            context: ./build
            dockerfile: siege
        container_name: "siege"
        stdin_open: true
        tty: true
        networks: 
            - app-external            

networks:
    app-external:
        driver: bridge
        internal: false
        
    app-internal:
        driver: bridge
        internal: true
